package com.meylot.domain.stats.types;

public enum ExpLevel {

    KTOS_NIEDOSWIADCZONY,
    KTOS_KTO_WIDZIAL_JUZ_TO_I_OWO,
    KTOS_KTO_PEWNIE_STAPA_PO_SWIECIE,
    KTOS_KTO_NIEJEDNO_WIDZIAL,
    KTOS_KTO_SWOJE_PRZEZYL,
    KTOS_DOSWIADCZONY,
    KTOS_KTO_WIELE_PRZESZEDL,
    KTOS_KTO_WIDZIAL_KAWAL_SWIATA,
    KTOS_BARDZO_DOSWIADCZONY,
    KTOS_KTO_ZWIEDZIL_CALY_SWIAT,
    KTOS_WIELCE_DOSWIADCZONY,
    KTOS_KTO_WIDZIAL_I_DOSWIADCZYL_WSZYSTKIEGO,
    OSOBA_OWIANA_LEGENDA,
    NONE
    ;

}
